### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown chat type with identity ALL when using skype.loadMoreChats(10)

### ISSUE THREAD

**Issue by MrPowerGamerBR** [samczsun/Skype4J#104]
```
Exception in thread "Thread-2" java.lang.IllegalArgumentException: Unknown chat type with identity ALL
        at com.samczsun.skype4j.internal.chat.ChatImpl.createChat(ChatImpl.java:307)
        at com.samczsun.skype4j.internal.SkypeImpl.loadChat(SkypeImpl.java:282)
        at com.samczsun.skype4j.internal.SkypeImpl.getOrLoadChat(SkypeImpl.java:295)
        at com.samczsun.skype4j.internal.SkypeImpl.loadMoreChats(SkypeImpl.java:181)
        at com.mrpowergamerbr.skykaty.SkyKatyApp.searchContactsByName(SkyKatyApp.java:201)
        at com.mrpowergamerbr.skykaty.SkyKatyApp.loginWith(SkyKatyApp.java:114)
        at com.mrpowergamerbr.skykaty.SkyKatyGUI$1$1.run(SkyKatyGUI.java:165)
        at java.lang.Thread.run(Unknown Source)
```

Code:

```
        try {
            if (skype.getAllChats().size() == 0) {
            userGroups = skype.loadMoreChats(10);
            } else {
                userGroups = skype.getAllChats();
            }
            System.out.println("loadMoreChats: " + userGroups.size());
            System.out.println("AllChats: " + skype.getAllChats().size());
        } catch (ConnectionException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
```

I don't know what kind of chat triggers that error, I didn't have this issue but another person had it in his Skype account.

**Comment by samczsun** [comment]
The error will now be properly handled via the ErrorHandler. If this occurs again please open a new issue with the error (and the JSON which should be included with the error)
