### ISSUE TITLE
Could I use email for log in?

### ISSUE THREAD

**Issue by labotsky** [samczsun/Skype4J#105]
Skype skype = new SkypeBuilder("sergey@gmail.com","password").withAllResources().build();

When I use email for login I have next error
Exception in thread "main" com.samczsun.skype4j.exceptions.ConnectionException: While logging in (401 Unauthorized)
    at com.samczsun.skype4j.internal.ExceptionHandler.generateException(ExceptionHandler.java:50)
    at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:372)
    at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:302)
    at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.post(Endpoints.java:282)
    at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:69)
    at com.simple.Bot.main(Bot.java:15)

Please, assist!

**Comment by samczsun** [comment]
Email logins are not currently supported

**Comment by SandroCoutinho** [comment]
Is there an ETA for this being supported?

**Comment by samczsun** [comment]
It depends. I've been very busy over the past few months and there just isn't enough time to dedicate to all of my projects - public and non-public. The quickest way for this to be implemented would likely be for someone else to PR a module to allow logging in using https://login.live.com or a code snippit which can be integrated. Otherwise it all depends when I get the time to reverse engineer the login protocol (or google and hope someone else has done it)

**Comment by SpraxDev** [comment]
> It depends. I've been very busy over the past few months and there just isn't enough time to dedicate to all of my projects - public and non-public. The quickest way for this to be implemented would likely be for someone else to PR a module to allow logging in using https://login.live.com or a code snippit which can be integrated. Otherwise it all depends when I get the time to reverse engineer the login protocol (or google and hope someone else has done it)

Did you get some time to add support for Microsoft-Accounts? It would be really great. Microsoft is to blame for forcing Users to use Microsoft-Accounts for new Skype-Accounts

**Comment by Reimius** [comment]
Is there any intent to do this.  I've looked through the code but don't really understand it well enough to implement the change suggested by samczsun.  I wish I was more familiar with what to do here.
