### ISSUE TITLE
skype.loadAllContacts() and skype.loadMoreChats(...) throwing "Not a number: "1"" error.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [samczsun/Skype4J#111]
```
Exception in thread "Thread-12" java.lang.UnsupportedOperationException: Not a number: "1"
    at com.eclipsesource.json.JsonValue.asInt(JsonValue.java:302)
    at com.samczsun.skype4j.internal.participants.info.ContactImpl.updateProfile(ContactImpl.java:280)
    at com.samczsun.skype4j.internal.participants.info.ContactImpl.<init>(ContactImpl.java:103)
    at com.samczsun.skype4j.internal.client.FullClient.loadAllContacts(FullClient.java:124)
    at com.mrpowergamerbr.skykaty.SkyKatyApp.loginWith(SkyKatyApp.java:192)
    at com.mrpowergamerbr.skykaty.view.LoginView$1$1.run(LoginView.java:72)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by MrPowerGamerBR** [comment]
The same error also is shown if I use "skype.loadMoreChats(50);"

```
Exception in thread "Thread-12" java.lang.UnsupportedOperationException: Not a number: "1"
    at com.eclipsesource.json.JsonValue.asInt(JsonValue.java:302)
    at com.samczsun.skype4j.internal.participants.info.ContactImpl.updateProfile(ContactImpl.java:280)
    at com.samczsun.skype4j.internal.participants.info.ContactImpl.<init>(ContactImpl.java:93)
    at com.samczsun.skype4j.internal.participants.info.ContactImpl.createContact(ContactImpl.java:49)
    at com.samczsun.skype4j.internal.chat.ChatGroup.load(ChatGroup.java:138)
    at com.samczsun.skype4j.internal.Factory.createChat(Factory.java:56)
    at com.samczsun.skype4j.internal.SkypeImpl.loadChat(SkypeImpl.java:288)
    at com.samczsun.skype4j.internal.SkypeImpl.getOrLoadChat(SkypeImpl.java:301)
    at com.samczsun.skype4j.internal.SkypeImpl.loadMoreChats(SkypeImpl.java:185)
    at com.mrpowergamerbr.skykaty.SkyKatyApp.loginWith(SkyKatyApp.java:194)
    at com.mrpowergamerbr.skykaty.view.LoginView$1$1.run(LoginView.java:73)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by MrPowerGamerBR** [comment]
Welp, actually a lot of things are throwing that error.

**Comment by ducc** [comment]
Found the issue, it's being resolved.

**Comment by samczsun** [comment]
Commit will be pushed soon
