### ISSUE TITLE
NullPointer exception when send message

### ISSUE THREAD

**Issue by labotsky** [samczsun/Skype4J#112]
java.lang.NullPointerException
    at com.samczsun.skype4j.internal.participants.UserImpl.getDisplayName(UserImpl.java:51)
    at com.simple.listeners.MessageListener.onMessageReceived(MessageListener.java:35)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.samczsun.skype4j.internal.RegisteredListener.handleEvent(RegisteredListener.java:36)
    at com.samczsun.skype4j.internal.SkypeEventDispatcher.callEvent(SkypeEventDispatcher.java:70)
    at com.samczsun.skype4j.internal.MessageType$2.handle(MessageType.java:106)
    at com.samczsun.skype4j.internal.MessageType$3.handle(MessageType.java:148)
    at com.samczsun.skype4j.internal.EventType$1.handle(EventType.java:38)
    at com.samczsun.skype4j.internal.threads.PollThread.lambda$run$1(PollThread.java:139)
    at com.samczsun.skype4j.internal.threads.PollThread$$Lambda$29/1669707104.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by samczsun** [comment]
It appears Skype4J couldn't load the contact info for the user, so no displayname was found. A commit will be pushed to return null properly when no contact exists
