### ISSUE TITLE
Skype decided to make the gender class com.eclipsesource.json.JsonLiteral

### ISSUE THREAD

**Issue by MrPowerGamerBR** [samczsun/Skype4J#113]
```
java.lang.IllegalArgumentException: Skype decided to make the gender class com.eclipsesource.json.JsonLiteral
    at com.samczsun.skype4j.internal.participants.info.ContactImpl.updateProfile(ContactImpl.java:287)
    at com.samczsun.skype4j.internal.participants.info.ContactImpl.<init>(ContactImpl.java:103)
    at com.samczsun.skype4j.internal.client.FullClient.loadAllContacts(FullClient.java:125)
    at com.mrpowergamerbr.skykaty.SkyKatyApp.loginWith(SkyKatyApp.java:204)
    at com.mrpowergamerbr.skykaty.view.LoginView$1$1.run(LoginView.java:131)
    at java.lang.Thread.run(Thread.java:745)
```

Using the latest commit.

**Comment by samczsun** [comment]
Skype is just trolling me at this point
