### ISSUE TITLE
Skype decided to make the gender class com.eclipsesource.json.JsonLiteral (Yes... the same error again)

### ISSUE THREAD

**Issue by MrPowerGamerBR** [samczsun/Skype4J#114]
```
java.lang.IllegalArgumentException: Skype decided to make the gender class com.eclipsesource.json.JsonLiteral
    at com.samczsun.skype4j.internal.participants.info.ContactImpl.updateProfile(ContactImpl.java:289)
    at com.samczsun.skype4j.internal.participants.info.ContactImpl.<init>(ContactImpl.java:103)
    at com.samczsun.skype4j.internal.client.FullClient.loadAllContacts(FullClient.java:125)
    at com.mrpowergamerbr.skykaty.SkyKatyApp.loginWith(SkyKatyApp.java:204)
    at com.mrpowergamerbr.skykaty.view.LoginView$1$1.run(LoginView.java:131)
    at java.lang.Thread.run(Thread.java:745)
```

(Well, it is the newer commit build because the line number changed (from 287 to 289))

**Comment by samczsun** [comment]
Yolo. I'll deal with this later when gender is an Enum or something
