### ISSUE TITLE
Problem, use Skype account without username

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [samczsun/Skype4J#142]
Hello, I have tryed to use a Skype account to connect with java but it hasn't worked. I have tryed with the email adress and the "live:". I have this error:
```
Cause: While logging in
        Response: 401 Unauthorized
        Begin Message 
{"status":{"code":40120,"text":"Authentication failed. Bad username or password."}}
        End message
```
But it has worked with my account (created with a username)
So, how can I connect java to my Skype account?

**Comment by Erezbiox1** [comment]
you can only use old skype accounts,
you can use guest tho

**Comment by Fuzay** [comment]
What do you mean by guest ?

**Comment by Manevolent** [comment]
You may find better luck trying out my solution posted here:

https://github.com/Delthas/JavaSkype/issues/24

Not sure if it will work with a live: username, but worth a try.

**Comment by Fuzay** [comment]
The thing with live: usernames is that they are not even working when I try to log on regular Skype :/

**Comment by simk0024** [comment]
I tried to use with my gmail address, live:_username_, but both cannot login. And now I can only receive this:
`java.io.IOException: Error while connecting to Skype: Too many failed authentication attempts with given username or IP.
	at fr.delthas.skype.WebConnector.generateTokens(WebConnector.java:171)
	at fr.delthas.skype.WebConnector.start(WebConnector.java:42)
	at fr.delthas.skype.Skype.connect(Skype.java:121)
	at fr.delthas.skype.Skype.connect(Skype.java:96)
	at com.skype.SkypeTest01.testConnect(SkypeTest01.java:13)
	at com.skype.SkypeTest01.main(SkypeTest01.java:34)`

What is the correct username should be used in the program?

**Comment by hunghd60115** [comment]
I have same issue with simk0024.

Login with my gmail, live:username... the same error return.

> `Error while connecting to Skype: Too many failed authentication attempts with given username or IP.`

Please help me fix this issue. 
I can login normal util today...
