### ISSUE TITLE
Errors during the login 

### ISSUE THREAD

**Issue by Euxiniar** [samczsun/Skype4J#156]
Hey ! 
I tried a simple code : 
``` Java
Skype skype = new SkypeBuilder("****", "****").withAllResources().build();
    	skype.login();
    	skype.subscribe();
    	skype.setVisibility(Visibility.ONLINE);
```

But I have these errors:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.samczsun.skype4j.internal.client.FullClient.hash(FullClient.java:202)
	at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:65)
	at fr.euxiniar.Skypebot.Skypebot.main(skype.login())
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 3 more
```

Any idea?

**Comment by metasonic** [comment]
Ola, last time i checked skype.setVisibility(Visibility.ONLINE) was no longer working. Everything else works, but after some time messages no longer come in due to the issue i submitted
