### ISSUE TITLE
Unsuccessful login on skype

### ISSUE THREAD

**Issue by techeaven** [samczsun/Skype4J#160]
When I enter the correct username and password, I get exception 404, Please, assist

com.samczsun.skype4j.exceptions.ConnectionException: While logging in (404 Not Found)
	at com.samczsun.skype4j.internal.ExceptionHandler.generateException(ExceptionHandler.java:50)
	at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:372)
	at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:302)
	at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.post(Endpoints.java:282)
	at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:69)
	at pers.techeaven.file_tools.skype.SkypeService.main(SkypeService.java:53)

![image](https://user-images.githubusercontent.com/44140173/70211302-b85af980-176f-11ea-860f-fa7bd3f33311.png)

**Comment by satyapal06** [comment]
I am also getting the same issue, any workaround?

**Comment by techeaven** [comment]
> 我也遇到同样的问题，有什么解决方法吗？

no
