### ISSUE TITLE
Exception after 2 days online - java.io.IOException: Server returned HTTP response code: 429

### ISSUE THREAD

**Issue by X-NoNAME** [samczsun/Skype4J#20]
Version 0.0.8-SNAPSHOT

```
java.io.IOException: Server returned HTTP response code: 429 for URL: https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1838)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at com.samczsun.skype4j.internal.SkypeImpl.login(SkypeImpl.java:274)
    at com.samczsun.skype4j.internal.SkypeImpl.access$700(SkypeImpl.java:36)
    at com.samczsun.skype4j.internal.SkypeImpl$1.run(SkypeImpl.java:143)
java.io.IOException: Server returned HTTP response code: 429 for URL: https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1838)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at com.samczsun.skype4j.internal.SkypeImpl.login(SkypeImpl.java:274)
    at com.samczsun.skype4j.internal.SkypeImpl.access$700(SkypeImpl.java:36)
    at com.samczsun.skype4j.internal.SkypeImpl$1.run(SkypeImpl.java:143)
```

**Comment by ducc** [comment]
@vemacs Posted a temporary fix for this issue: https://gist.github.com/vemacs/aa1565456b76022ed847

This logs into the account every 30 mins, and once logged in, swaps the old login session to the new session ensuring no downtime. I have been running this for 7 days without failure.

Hopefully a permanent fix will be made soon.
