### ISSUE TITLE
How to start an NPE farm

### ISSUE THREAD

**Issue by ducc** [samczsun/Skype4J#4]
Adding users always gives this beautiful exception :3

```
Jul 13, 2015 11:46:22 PM com.samczsun.skype4j.internal.SkypeImpl$2$1 run
SEVERE: Exception while handling message
java.lang.NullPointerException
    at com.samczsun.skype4j.events.chat.user.UserEvent.<init>(UserEvent.java:10)
    at com.samczsun.skype4j.events.chat.user.UserAddEvent.<init>(UserAddEvent.java:9)
    at com.samczsun.skype4j.internal.MessageType$11.handle(MessageType.java:189)
    at com.samczsun.skype4j.internal.SkypeImpl$2$1.run(SkypeImpl.java:190)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Jul 13, 2015 11:46:22 PM com.samczsun.skype4j.internal.SkypeImpl$2$1 run
SEVERE: {"eventMessages":[{"id":1676,"type":"EventMessage","resourceType":"NewMessage","time":"2015-07-13T22:46:22Z","resourceLink":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/19:707a14af6d42433c93a8d9d4db1726e7@thread.skype/messages/1436827581841","resource":{"id":"1436827581841","ackrequired":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/ALL/messages/1436827581841/ack","originalarrivaltime":"2015-07-13T22:46:21.841Z","messagetype":"ThreadActivity/AddMember","conversationLink":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/19:707a14af6d42433c93a8d9d4db1726e7@thread.skype","composetime":"2015-07-13T22:46:21.841Z","contentformat":"FN=MS%20Shell%20Dlg; EF=; CO=0; CS=0; PF=0","content":"<addmember><eventtime>1436827581841</eventtime><initiator>8:joepwnsall1</initiator><target>8:spongybacon</target></addmember>","type":"Message","isactive":true,"threadtopic":"spongybacon, joepwnsall1, spongybot","from":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/contacts/19:707a14af6d42433c93a8d9d4db1726e7@thread.skype"}}]}
Jul 13, 2015 11:46:51 PM com.samczsun.skype4j.internal.SkypeImpl$2$1 run
SEVERE: Exception while handling message
java.lang.NullPointerException
    at com.samczsun.skype4j.events.chat.user.UserEvent.<init>(UserEvent.java:10)
    at com.samczsun.skype4j.events.chat.user.UserAddEvent.<init>(UserAddEvent.java:9)
    at com.samczsun.skype4j.events.chat.user.MultiUserAddEvent.<init>(MultiUserAddEvent.java:12)
    at com.samczsun.skype4j.internal.MessageType$11.handle(MessageType.java:191)
    at com.samczsun.skype4j.internal.SkypeImpl$2$1.run(SkypeImpl.java:190)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Jul 13, 2015 11:46:51 PM com.samczsun.skype4j.internal.SkypeImpl$2$1 run
SEVERE: {"eventMessages":[{"id":1681,"type":"EventMessage","resourceType":"NewMessage","time":"2015-07-13T22:46:51Z","resourceLink":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/19:707a14af6d42433c93a8d9d4db1726e7@thread.skype/messages/1436827610731","resource":{"id":"1436827610731","ackrequired":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/ALL/messages/1436827610731/ack","originalarrivaltime":"2015-07-13T22:46:50.731Z","messagetype":"ThreadActivity/AddMember","conversationLink":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/19:707a14af6d42433c93a8d9d4db1726e7@thread.skype","composetime":"2015-07-13T22:46:50.731Z","contentformat":"FN=MS%20Shell%20Dlg; EF=; CO=0; CS=0; PF=0","content":"<addmember><eventtime>1436827610731</eventtime><initiator>8:joepwnsall1</initiator><target>8:spongybacon</target><target>8:codebeasts</target></addmember>","type":"Message","isactive":true,"threadtopic":"codebeasts, spongybacon, joepwnsall1, spongybot","from":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/contacts/19:707a14af6d42433c93a8d9d4db1726e7@thread.skype"}}]}
```

enjoi bb

**Comment by juIio** [comment]
Why would you want to remove such a beautiful exception?

**Comment by ducc** [comment]
bcus then i cant ban everyone and keep them banned and then take over the world
