### ISSUE TITLE
Error when trying to load a chat that has a join.skype.com link enabled

### ISSUE THREAD

**Issue by ctian1** [samczsun/Skype4J#43]
trying to loadChat() the identity gives this stack trace:

```
SEVERE: Error while handling event
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.samczsun.skype4j.internal.RegisteredListener.handleEvent(RegisteredListener.java:37)
    at com.samczsun.skype4j.internal.SkypeEventDispatcher.callEvent(SkypeEventDispatcher.java:67)
    at com.samczsun.skype4j.internal.SkypeEventDispatcher.callEvent(SkypeEventDispatcher.java:59)
    at com.samczsun.skype4j.internal.MessageType$3.handle(MessageType.java:95)
    at com.samczsun.skype4j.internal.MessageType$2.handle(MessageType.java:78)
    at com.samczsun.skype4j.internal.EventType$1.handle(EventType.java:35)
    at com.samczsun.skype4j.internal.SkypeImpl$3$1.run(SkypeImpl.java:410)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.samczsun.skype4j.internal.chat.ChatGroup.load(ChatGroup.java:78)
    at com.samczsun.skype4j.internal.chat.ChatImpl.<init>(ChatImpl.java:57)
    at com.samczsun.skype4j.internal.chat.ChatGroup.<init>(ChatGroup.java:50)
    at com.samczsun.skype4j.internal.chat.ChatImpl.createChat(ChatImpl.java:130)
    at com.samczsun.skype4j.internal.SkypeImpl.loadChat(SkypeImpl.java:449)
    at io.github.pangeacake.pangeabot.PangeaBot$1.onMessage(PangeaBot.java:313)
    ... 13 more
```

**Comment by ctian1** [comment]
I'm pretty sure this is the cause: after disabling public joining in the chat (which disables the link) the bot is able to access the chat and works normally.

In chats with join.skype.com links, the bot does not even receive MessageEvents from the chat.

**Comment by samczsun** [comment]
Can you please try using the latest version of the code? Line 78 is a close bracket currently.

https://github.com/samczsun/Skype4J/blob/master/src/main/java/com/samczsun/skype4j/internal/chat/ChatGroup.java#L78

**Comment by ctian1** [comment]
I was using the version prior to the licensing change, so the line difference was because of the license header. I'll try again with the latest version once I get back to my computer, but the result will probably be the same.

Relevant line of code in older version:
https://github.com/samczsun/Skype4J/blob/4a58eb6805c4d405312497c197b45ed081eb8109/src/main/java/com/samczsun/skype4j/internal/chat/ChatGroup.java#L78

**Comment by ctian1** [comment]
New stacktrace:

```
SEVERE: Error while handling event
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.samczsun.skype4j.internal.RegisteredListener.handleEvent(RegisteredListener.java:36)
    at com.samczsun.skype4j.internal.SkypeEventDispatcher.callEvent(SkypeEventDispatcher.java:66)
    at com.samczsun.skype4j.internal.SkypeEventDispatcher.callEvent(SkypeEventDispatcher.java:58)
    at com.samczsun.skype4j.internal.MessageType$3.handle(MessageType.java:94)
    at com.samczsun.skype4j.internal.MessageType$2.handle(MessageType.java:77)
    at com.samczsun.skype4j.internal.EventType$1.handle(EventType.java:34)
    at com.samczsun.skype4j.internal.SkypeImpl$3$1.run(SkypeImpl.java:409)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.samczsun.skype4j.internal.chat.ChatGroup.load(ChatGroup.java:77)
    at com.samczsun.skype4j.internal.chat.ChatImpl.<init>(ChatImpl.java:56)
    at com.samczsun.skype4j.internal.chat.ChatGroup.<init>(ChatGroup.java:49)
    at com.samczsun.skype4j.internal.chat.ChatImpl.createChat(ChatImpl.java:129)
    at com.samczsun.skype4j.internal.SkypeImpl.loadChat(SkypeImpl.java:448)
    at io.github.pangeacake.pangeabot.PangeaBot$1.onMessage(PangeaBot.java:313)
    ... 14 more
```

**Comment by samczsun** [comment]
I think I see what's going on. The code is being compiled to run in the constructor, but the constructor is called after load() due to the super call. I'll push a fix for this so you can test it out

**Comment by ctian1** [comment]
Seems to be working. Thanks for fix!
