### ISSUE TITLE
skype.login()

### ISSUE THREAD

**Issue by frezec** [samczsun/Skype4J#56]
Win 8.1 VS 2013 skype4j-0.1.5 C#

java.lang.RuntimeException не обработано
  HResult=-2146233088
  Message=java.lang.UnsupportedOperationException: Not a string: 78790
  Source=Skype4j
  StackTrace:
       в com.samczsun.skype4j.internal.client.FullClient.login(String[] )
       в com.samczsun.skype4j.internal.client.FullClient.login()
       в Skype.Program.Main(String[] args) в c:\Users\El'bor\Documents\Visual Studio 2013\Projects\Skypebeta\Skypebeta\Program.cs:строка 51
       в System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       в System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       в Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       в System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       в System.Threading.ThreadHelper.ThreadStart()
  InnerException: java.lang.UnsupportedOperationException
       HResult=-2146233088
       Message=Not a string: 78790
       Source=Skype4j
       StackTrace:
            в com.eclipsesource.json.JsonValue.asString()
            в com.samczsun.skype4j.internal.client.FullClient.registerWebSocket()
            в com.samczsun.skype4j.internal.client.FullClient.login(String[] )
       InnerException:

**Comment by arthur-kalmykov** [comment]
Same exception 
win 7 x64, Intellij Idea 15.0.1 

java.lang.RuntimeException: java.lang.UnsupportedOperationException: Not a string: 78942
    at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:269)
    at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:234)
    at skype.SkypeController.signIn(SkypeController.java:68)
    at ui.LoginForm.doLogin(LoginForm.java:61)
    at ui.LoginForm.lambda$placeComponents$22(LoginForm.java:51)
    at ui.LoginForm$$Lambda$13/1154002927.actionPerformed(Unknown Source)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.UnsupportedOperationException: Not a string: 78942
    at com.eclipsesource.json.JsonValue.asString(JsonValue.java:365)
    at com.samczsun.skype4j.internal.client.FullClient.registerWebSocket(FullClient.java:379)
    at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:267)
    ... 41 more

**Comment by DarkSeraphim** [comment]
@arthur-kalmykov @frezec try the latest version from the repo, I was able to log in without issues.
