### ISSUE TITLE
Error when using Message.fromHtml

### ISSUE THREAD

**Issue by ctian1** [samczsun/Skype4J#60]
arguments:

```
<font color="#55FF55">╔══════<font color="#000000"> <font color="#555555"><i>[<font color="#5555FF"></i><i>US<font color="#555555"></i><i>] <font color="#664400"></i><b>Overcast <font color="#FFAA00"></b><b>Network <font color="#000000"></b>⁚<font color="#55FF55">══════╗
<font color="#55FF55">╚════<font color="#000000">⁚ <font color="#55FFFF"><i>New players are VIP for 7 days! <font color="#000000"></i>⁚<font color="#55FF55">════╝

```

stacktrace:

```
[SEVERE] [Mon Jan 04 17:20:21 PST 2016] Could not handle class com.samczsun.skype4j.events.chat.message.MessageReceivedEvent
java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:592)
    at java.lang.Integer.parseInt(Integer.java:615)
    at com.samczsun.skype4j.formatting.RichText$2.lambda$new$8(RichText.java:111)
    at com.samczsun.skype4j.formatting.RichText$2$$Lambda$34/1415452897.test(Unknown Source)
    at com.samczsun.skype4j.formatting.RichText.hasTag(RichText.java:443)
    at com.samczsun.skype4j.formatting.RichText.parse(RichText.java:423)
    at com.samczsun.skype4j.formatting.RichText.fromHtml(RichText.java:391)
    at com.samczsun.skype4j.formatting.Message.fromHtml(Message.java:112)
    at io.github.pangeacake.pangeabot.PangeaBot$1.onMessage(PangeaBot.java:223)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.samczsun.skype4j.internal.RegisteredListener.handleEvent(RegisteredListener.java:36)
    at com.samczsun.skype4j.internal.SkypeEventDispatcher.callEvent(SkypeEventDispatcher.java:80)
    at com.samczsun.skype4j.internal.SkypeEventDispatcher.callEvent(SkypeEventDispatcher.java:61)
    at com.samczsun.skype4j.internal.MessageType$2.handle(MessageType.java:121)
    at com.samczsun.skype4j.internal.MessageType$4.handle(MessageType.java:169)
    at com.samczsun.skype4j.internal.EventType$1.handle(EventType.java:38)
    at com.samczsun.skype4j.internal.threads.PollThread.lambda$run$21(PollThread.java:147)
    at com.samczsun.skype4j.internal.threads.PollThread$$Lambda$20/1295904827.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ctian1** [comment]
also, this worked ~1 month ago, probably due to the latest fromHtml changes

**Comment by ctian1** [comment]
Hm.. now I'm getting a 'While sending message (400 Bad Request)' error with the following.. skype pls

```
<font size="12" color="#55FF55">╔══════<font size="12" color="#000000"> <font size="12" color="#555555"><i>[<font size="12" color="#5555FF"></i><i>US<font size="12" color="#555555"></i><i>] <font size="12" color="#664400"></i><b>Overcast <font size="12" color="#FFAA00"></b><b>Network <font size="12" color="#000000"></b>⁚<font size="12" color="#55FF55">══════╗
<font size="12" color="#55FF55">╚════<font size="12" color="#000000">⁚ <font size="12" color="#55FFFF"><i>New players are VIP for 7 days! <font size="12" color="#000000"></i>⁚<font size="12" color="#55FF55">════╝
```

**Comment by ctian1** [comment]
Ah, lemme clarify: the 400 error was after I added the size="12" attribute, but before that the stacktrace occured.

**Comment by samczsun** [comment]
Assuming the issue is fixed

**Comment by ctian1** [comment]
Issue doesn't seem to be fixed

No errors, I'm trying to send this:

```
<font size="12" color="#55FF55">╔══════<font size="12" color="#000000"> <font size="12" color="#555555"><i>[<font size="12" color="#5555FF"></i><i>US<font size="12" color="#555555"></i><i>] <font size="12" color="#664400"></i><b>Overcast <font size="12" color="#FFAA00"></b><b>Network <font size="12" color="#000000"></b>⁚<font size="12" color="#55FF55">══════╗
<font size="12" color="#55FF55">╚═══<font size="12" color="#000000">⁚⁚⁚⁚⁚⁚⁚⁚ <font size="12" color="#FF55FF"><b>Ranked Servers<font size="12" color="#FFFFFF"></b> have arrived! <font size="12" color="#000000">⁚⁚⁚⁚⁚⁚⁚⁚⁚<font size="12" color="#55FF55">═══╝
```

**Comment by samczsun** [comment]
What code are you using to send it?

**Comment by ctian1** [comment]
Using `chat.sendMessage(Message.fromHtml(motd));`

**Comment by ctian1** [comment]
I also tried this:

```
<font color="#55FF55">╔══════<font color="#000000"> <font color="#555555"><i>[<font color="#5555FF"></i><i>US<font color="#555555"></i><i>] <font color="#664400"></i><b>Overcast <font color="#FFAA00"></b><b>Network <font color="#000000"></b>⁚<font color="#55FF55">══════╗
<font color="#55FF55">╚════<font color="#000000">⁚ <font color="#55FFFF"><i>New players are VIP for 7 days! <font color="#000000"></i>⁚<font color="#55FF55">════╝
```

same result, no errors, no message

**Comment by DarkSeraphim** [comment]
@pangeacake your HTML is as broken as it could be.

**Comment by ctian1** [comment]
Nevermind, it was my fault because of the mangled HTML I didn't notice. Thanks
