### ISSUE TITLE
Spam stack trace on latest version

### ISSUE THREAD

**Issue by ducc** [samczsun/Skype4J#81]
```
Error! SESSION_ACTIVE class com.samczsun.skype4j.exceptions.ConnectionException While submitting active (404 Not Found) false
com.samczsun.skype4j.exceptions.ConnectionException: While submitting active (404 Not Found)
        at com.samczsun.skype4j.internal.ExceptionHandler.generateException(ExceptionHandler.java:50)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:372)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:302)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.post(Endpoints.java:286)
        at com.samczsun.skype4j.internal.threads.ActiveThread.run(ActiveThread.java:43)
```

Only seems to happen on my dedi. Does not affect functionality, just printed every few secs.

**Comment by ctian1** [comment]
Since when do you use skype4j again :P

**Comment by ducc** [comment]
I've been using it for a while, haven't touched Skype much really.

**Comment by ducc** [comment]
Noticed that on this version setting visibility to `Visibility.ONLINE` doesn't work. This might be related?

**Comment by samczsun** [comment]
Turns out built-in relogging function is still breaking this

**Comment by ducc** [comment]
gg

**Comment by techeaven** [comment]
hello , Is this problem resolved? I also encountered this problem
