### ISSUE TITLE
Guest user can not reply to messages

### ISSUE THREAD

**Issue by hermansc** [samczsun/Skype4J#85]
Example implementation:

```
Skype skype = new SkypeBuilder("Skype4JGuest").withChat(<id>).withAllResources().build();
skype.login();
skype.getEventDispatcher().registerListener(new Listener() {
  @EventHandler
  public void onMessage(MessageReceivedEvent e) {
    if (! e.getMessage().getContent().toString().equals("hello")) { return; }
    Chat c = e.getMessage.getChat();
    c.sendMessage(Message.create().with(Text.plain("hey!")));
  }
});
```

Throws exception:

```
[SEVERE] [<date>] Error while handling event
java.lang.reflect.InvocationTargetException
        (...)
    at com.samczsun.skype4j.internal.RegisteredListener.handleEvent(RegisteredListener.java:36)
    at com.samczsun.skype4j.internal.SkypeEventDispatcher.callEvent(SkypeEventDispatcher.java:75)
    at com.samczsun.skype4j.internal.MessageType$2.handle(MessageType.java:121)
    at com.samczsun.skype4j.internal.MessageType$4.handle(MessageType.java:169)
    at com.samczsun.skype4j.internal.EventType$1.handle(EventType.java:38)
    at com.samczsun.skype4j.internal.threads.PollThread.lambda$run$1(PollThread.java:139)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: User must not be null
    at org.jsoup.helper.Validate.notNull(Validate.java:26)
    at com.samczsun.skype4j.internal.chat.messages.ChatMessageImpl.createMessage(ChatMessageImpl.java:86)
    at com.samczsun.skype4j.internal.chat.ChatImpl.sendMessage(ChatImpl.java:84)
    (...)
    ... 13 more
```

The null pointer exception is caused by the user object being `null`, which I think is because the `getUser()` is using the username returned by `msg.getClient().getUsername()` - which equals "Skype4JGuest" instead of the username assigned by Skype which you can expose by doing:

```
for (User u : msg.getAllUsers()) {
    System.out.println(u.getUsername())
}
```

It will return something along the lines of: `guest:Skype4JGuest_831fdf79`.

You can also trigger the nullpointerexception by trying to use the object returned by: `msg.getChat().getSelf()`.

**Comment by hermansc** [comment]
You're a star. Thanks for the fix, and for this great library - having great fun and the code is a pleasure to read.
