### ISSUE TITLE
504

### ISSUE THREAD

**Issue by ghost** [samczsun/Skype4J#91]
hey guys. I'm getting this problem when trying to send an image from my application.
Any ideas why this is happening?

```

com.samczsun.skype4j.exceptions.ConnectionException:
                Cause: While getting upload status
                Response: 504 Gateway Timeout
                Begin Message

There was no message

                End message

        at com.samczsun.skype4j.internal.ExceptionHandler.generateException(Exce
ptionHandler.java:101)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(En
dpoints.java:377)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.get(Endpoi
nts.java:275)
        at com.samczsun.skype4j.internal.Utils.upload(Utils.java:86)
        at com.samczsun.skype4j.internal.Utils.uploadImage(Utils.java:58)
        at com.samczsun.skype4j.internal.chat.ChatImpl.sendImage(ChatImpl.java:1
28)
        at com.samczsun.skype4j.internal.chat.ChatImpl.sendImage(ChatImpl.java:1
24)
        at haven.paragon.automations.SkypeImageSender.sendImage(SkypeImageSender
.java:22)
```

**Comment by samczsun** [comment]
http://stackoverflow.com/questions/261536/http-status-504
