### ISSUE TITLE
Removing the topic makes it not fire the event

### ISSUE THREAD

**Issue by ducc** [samczsun/Skype4J#92]
```
[SEVERE] [Mon Apr 18 02:01:27 UTC 2016] Error while handling event
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.samczsun.skype4j.internal.RegisteredListener.handleEvent(RegisteredListener.java:36)
        at com.samczsun.skype4j.internal.SkypeEventDispatcher.callEvent(SkypeEventDispatcher.java:75)
        at com.samczsun.skype4j.internal.MessageType$15.handle(MessageType.java:457)
        at com.samczsun.skype4j.internal.EventType$1.handle(EventType.java:38)
        at com.samczsun.skype4j.internal.threads.PollThread.lambda$run$19(PollThread.java:139)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: String input must not be null
        at org.jsoup.helper.Validate.notNull(Validate.java:26)
        at org.jsoup.parser.TreeBuilder.initialiseParse(TreeBuilder.java:26)
        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:42)
        at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:53)
        at org.jsoup.parser.Parser.parse(Parser.java:90)
        at org.jsoup.Jsoup.parse(Jsoup.java:58)
        at io.sponges.bot.client.skype.Client.onTopicUpdate(Client.java:319)
        ... 11 more
```

**Comment by Sponges** [comment]
https://vgy.me/v2U4lL.gif

**Comment by ducc** [comment]
nvm forgot a null check
