### ISSUE TITLE
ConnectionException:{"errorCode":201,"message":"To field is invalid"}

### ISSUE THREAD

**Issue by Doran1990** [samczsun/Skype4J#99]
I can't send message to some firends, but I can send message with skype or web skype.
the error is : pls help me how to slove it.
com.samczsun.skype4j.exceptions.ConnectionException: 
        Cause: While sending message
        Response: 400 Bad Request
        Begin Message 

{"errorCode":201,"message":"To field is invalid"}

```
    End message

at com.samczsun.skype4j.internal.ExceptionHandler.generateException(ExceptionHandler.java:101)
at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:377)
at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:307)
at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.post(Endpoints.java:291)
at com.samczsun.skype4j.internal.chat.ChatImpl.sendMessage(ChatImpl.java:85)
```

**Comment by ducc** [comment]
Code please :)

**Comment by Doran1990** [comment]
This is my code: I get all contacts ,and send private message
Collection<Contact> contacts =  skype.getAllContacts();
Object[] ary = contacts.toArray();
for(int i =0;i<ary.length;i++){

Contact contact = (Contact)ary[i];
Chat chat = contact.getPrivateConversation();
ChatMessage chatMessage = null;
chatMessage = chat.sendMessage(Message.create().with(Text.plain(msg)).with(Text.rich(link).withLink(link)));
}

**Comment by Doran1990** [comment]
I send message to all of contacts,sometime get the error:
ConnectionException: Cause: While sending message
        Response: 504 Gateway Timeout
        Begin Message 

{"errorCode":507,"message":"Failure due to: AclNotAvailable."}

```
    End message
```

at com.samczsun.skype4j.internal.ExceptionHandler.generateException(ExceptionHandler.java:101)
    at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:377)
    at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:307)
    at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.post(Endpoints.java:291)
    at com.samczsun.skype4j.internal.chat.ChatImpl.sendMessage(ChatImpl.java:85)

**Comment by ducc** [comment]
Whilst we are waiting for @samczsun, why not use a for loop for iterating contacts?

``` java
for (Contact contact : skype.getAllContacts()) {
  // do what you want for each contact here
}
```

**Comment by Doran1990** [comment]
@Sponges  sure, can use iterating.

**Comment by Doran1990** [comment]
any body help me?

**Comment by Doran1990** [comment]
it seem the error occur when send message to msn friend

**Comment by samczsun** [comment]
Could you elaborate on what you mean by "msn friend"?
